# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.26'

      - name: Install LLVM and Clang
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-20-dev clang-20

      - name: Build
        run: go build -v ./...

      - name: Run examples
        run: |
          mkdir -p build
          
          go run -tags=llvm20 . -s examples/fib.k -o build/fib.o
          clang-20 build/fib.o examples/lib.c -o build/fib
          ./build/fib
          
          go run -tags=llvm20 . -s examples/std.k -o build/std.o
          clang-20 build/std.o -o build/std
          ./build/std
